### ISSUE TITLE
Try to build v8 on Windows with Visual Studio 2017

### ISSUE THREAD

**Issue by IAmNotHanni** [inexorgame/entity-system#132]
Let's try to build [v8](https://github.com/v8/v8) on Windows using Visual Studio 2017.

I will use this tutorial:
https://blog.angularindepth.com/how-to-build-v8-on-windows-and-not-go-mad-6347c69aacd4

I will write down step by step why I did in this ticket.

**Comment by IAmNotHanni** [comment]
Ok so I just cloned v8 from the official GitHub page.
I will use MS Visual Studio 2017 instead of 2015 which is used in the tutorial.

**Comment by IAmNotHanni** [comment]
I downloaded `depot_tools` from this link: https://storage.googleapis.com/chrome-infra/depot_tools.zip

**Comment by IAmNotHanni** [comment]
I made sure I extracted it correctly so the `.git` folder is there.

**Comment by IAmNotHanni** [comment]
I added `G:\Inexor\depot_tools` to the system variable `Path`.

**Comment by IAmNotHanni** [comment]
I added it to the system variables not to the user variables.

**Comment by IAmNotHanni** [comment]
I added the following things to the **user variables not the system variables**:

```
DEPOT_TOOLS_WIN_TOOLCHAIN=0
GYP_MSVS_VERSION =2015
```

**Comment by IAmNotHanni** [comment]
In contrast to the tutorial, I set the Visual Studio version to `2017` and not `2015`  since I have this one installed.

**Comment by IAmNotHanni** [comment]
Ok so I opened a commant line with administrator rights and run the command `gclient`.
This takes some time to download the neccesary dependencies.
It looks like it worked. This is the result:

![test23](https://user-images.githubusercontent.com/7914428/67641023-e17da400-f8fe-11e9-94ab-15c3cf4ff2f7.jpg)

**Comment by IAmNotHanni** [comment]
I made sure that `python.bat` comes before `python.exe` when I execute `where python` in the console:
![test33](https://user-images.githubusercontent.com/7914428/67641083-65379080-f8ff-11e9-8760-2e4854ddd5b5.png)

**Comment by IAmNotHanni** [comment]
The `v8` download using GitHub Desktop has finished. Let's try to build.

**Comment by IAmNotHanni** [comment]
Currently I have Python `3.8.0` installed. Im not sure if this is too new for these build scripts.

**Comment by IAmNotHanni** [comment]
I run `gclient sync` in `G:\Inexor\v8`.

**Comment by IAmNotHanni** [comment]
I found this: https://stackoverflow.com/questions/8684282/gclient-runhooks-fails

**Comment by IAmNotHanni** [comment]
I executed the commands:

```
G:\Inexor\v8>gclient sync
Error: client not configured; see 'gclient config'
G:\Inexor\v8>gclient config http://src.chromium.org/svn/trunk/src
G:\Inexor\v8>gclient runhooks
G:\Inexor\v8>gclient sync
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_kx6pmm' in 'G:\Inexor\v8'
1>Cloning into 'G:\Inexor\v8\_gclient_src_kx6pmm'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_kx6pmm"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_kx6pmm' in 'G:\Inexor\v8' attempt 2 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_kx6pmm'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_kx6pmm"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_kx6pmm' in 'G:\Inexor\v8' attempt 3 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_kx6pmm'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_kx6pmm"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_kx6pmm' in 'G:\Inexor\v8' attempt 4 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_kx6pmm'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_kx6pmm"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_pk6yea' in 'G:\Inexor\v8'
1>Cloning into 'G:\Inexor\v8\_gclient_src_pk6yea'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_pk6yea"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_pk6yea' in 'G:\Inexor\v8' attempt 2 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_pk6yea'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_pk6yea"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_pk6yea' in 'G:\Inexor\v8' attempt 3 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_pk6yea'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_pk6yea"' in G:\Inexor\v8 failed; will retry after a short nap...
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\Inexor\v8\_gclient_src_pk6yea' in 'G:\Inexor\v8' attempt 4 / 4
1>Cloning into 'G:\Inexor\v8\_gclient_src_pk6yea'...
1>fatal: repository 'http://src.chromium.org/svn/trunk/src/' not found
1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "http://src.chromium.org/svn/trunk/src" "G:\Inexor\v8\_gclient_src_pk6yea"' in G:\Inexor\v8 failed; will retry after a short nap...
Syncing projects: 100% ( 1/ 1) src

src (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00]
Traceback (most recent call last):
  File "G:\Inexor\depot_tools\gclient_scm.py", line 1045, in _Clone
    print_stdout=print_stdout, filter_fn=filter_fn)
  File "G:\Inexor\depot_tools\gclient_scm.py", line 1382, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "G:\Inexor\depot_tools\gclient_utils.py", line 622, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\\Inexor\\v8\\_gclient_src_kx6pmm' returned non-zero exit status 128 in G:\Inexor\v8
[0:00:17] _____ Conflicting directory found in G:\Inexor\v8\src. Moving to G:\Inexor\v8\_bad_scm\srcsdg907.
[0:00:17]
Traceback (most recent call last):
  File "G:\Inexor\depot_tools\gclient_scm.py", line 1045, in _Clone
    print_stdout=print_stdout, filter_fn=filter_fn)
  File "G:\Inexor\depot_tools\gclient_scm.py", line 1382, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "G:\Inexor\depot_tools\gclient_utils.py", line 622, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\\Inexor\\v8\\_gclient_src_pk6yea' returned non-zero exit status 128 in G:\Inexor\v8
----------------------------------------
Error: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress http://src.chromium.org/svn/trunk/src G:\\Inexor\\v8\\_gclient_src_pk6yea' returned non-zero exit status 128 in G:\Inexor\v8


Warnings:
Conflicting directory G:\Inexor\v8\src moved to G:\Inexor\v8\_bad_scm\srcsdg907.
G:\Inexor\v8>
```

**Comment by IAmNotHanni** [comment]
I created the following .bat file in the v8 directory and executed it:

```
set DEPOT_TOOLS_WIN_TOOLCHAIN=0
set GYP_MSVS_VERSION = 2017
gclient config https://chromium.googlesource.com/chromium/src.git
gclient sync
gclient runhooks
cd src
ninja -C out\Debug chrome
```

**Comment by IAmNotHanni** [comment]
Ok looks like its very important to run `gclient` without any arguments because this will download the python 2.7 enviroment which includes python.bat.
If you miss this step, the command `where python` will only find python.exe.

**Comment by IAmNotHanni** [comment]
I executed `fetch v8`:

```
G:\Inexor\v8>fetch v8
Running: 'C:\Users\Johannes\.vpython-root\fb192b\Scripts\python.exe' 'G:\Inexor\depot_tools\gclient.py' root
Running: 'C:\Users\Johannes\.vpython-root\fb192b\Scripts\python.exe' 'G:\Inexor\depot_tools\gclient.py' config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: 'C:\Users\Johannes\.vpython-root\fb192b\Scripts\python.exe' 'G:\Inexor\depot_tools\gclient.py' sync --with_branch_heads
1>________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git G:\Inexor\v8\_gclient_v8_osjz64' in 'G:\Inexor\v8'
1>Cloning into 'G:\Inexor\v8\_gclient_v8_osjz64'...
1>remote: Sending approximately 898.25 MiB ...
1>remote: Counting objects: 7660, done
1>remote: Total 713483 (delta 567439), reused 713483 (delta 567439)
1>Receiving objects: 100% (713483/713483), 898.25 MiB | 2.89 MiB/s, done.
1>Resolving deltas: 100% (567439/567439), done.

[0:07:10] Still working on:
[0:07:10]   v8
1>Syncing projects:   0% ( 0/ 2)
[0:07:11] Still working on:
[0:07:11]   v8
6>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://chromium.googlesource.com/v8/deps/third_party/mozilla-tests.git" "G:\Inexor\v8\v8\test\mozilla\_gclient_data_8mowxh"' in G:\Inexor\v8 failed; will retry after a short nap...
Syncing projects:  92% (24/26) v8/third_party/protobuf
[0:10:48] Still working on:
[0:10:48]   v8/test/test262/data
[0:10:48]   v8/third_party/icu

[0:10:58] Still working on:
[0:10:58]   v8/test/test262/data
[0:10:58]   v8/third_party/icu

[0:11:04] Still working on:
[0:11:04]   v8/test/test262/data
[0:11:04]   v8/third_party/icu
Syncing projects:  96% (25/26) v8/test/test262/data
[0:12:14] Still working on:
[0:12:14]   v8/third_party/icu

[0:12:19] Still working on:
[0:12:19]   v8/third_party/icu
Syncing projects: 100% (26/26), done.
Hook 'vpython.bat v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' took 46.06 secs
Running hooks:  12% ( 3/25) clang_format_win
________ running 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s v8/buildtools/win/clang-format.exe.sha1' in 'G:\Inexor\v8'
0> Downloading v8/buildtools/win/clang-format.exe...
Downloading 1 files took 55.707000 second(s)
Hook 'download_from_google_storage --no_resume --platform=win32 --no_auth --bucket chromium-clang-format -s v8/buildtools/win/clang-format.exe.sha1' took 55.81 secs
Running hooks:  32% ( 8/25) wasm_spec_tests
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in 'G:\Inexor\v8'
0> Downloading v8/test/wasm-spec-tests/tests.tar.gz...
0> Extracting 477 entries from v8/test/wasm-spec-tests/tests.tar.gz to v8/test/wasm-spec-tests/tests
Downloading 1 files took 9.002000 second(s)
Running hooks:  36% ( 9/25) wasm_js
________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in 'G:\Inexor\v8'
0> Downloading v8/test/wasm-js/tests.tar.gz...
0> Extracting 124 entries from v8/test/wasm-js/tests.tar.gz to v8/test/wasm-js/tests
Downloading 1 files took 7.750000 second(s)
Running hooks:  76% (19/25) clang
________ running 'vpython.bat v8/tools/clang/scripts/update.py' in 'G:\Inexor\v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-373424-64a362e7-1.tgz .......... Done.
Traceback (most recent call last):
  File "v8/tools/clang/scripts/update.py", line 336, in <module>
    sys.exit(main())
  File "v8/tools/clang/scripts/update.py", line 332, in main
    return UpdateClang()
  File "v8/tools/clang/scripts/update.py", line 270, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "v8/tools/clang/scripts/update.py", line 230, in CopyDiaDllTo
    GetWinSDKDir()
  File "v8/tools/clang/scripts/update.py", line 204, in GetWinSDKDir
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 528, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 90, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 203, in DetectVisualStudioPath
    ' not found.' % version_as_year)
Exception: Visual Studio Version 2017 (from GYP_MSVS_VERSION) not found.
Error: Command 'vpython.bat v8/tools/clang/scripts/update.py' returned non-zero exit status 1 in G:\Inexor\v8
Hook 'vpython.bat v8/tools/clang/scripts/update.py' took 18.13 secs
Subprocess failed with return code 2.

```

**Comment by IAmNotHanni** [comment]
I executed `gclient sync:

```
G:\Inexor\v8>cd v8

G:\Inexor\v8\v8>gclient sync
Syncing projects: 100% (26/26), done.
Running hooks:  76% (19/25) clang
________ running 'vpython.bat v8/tools/clang/scripts/update.py' in 'G:\Inexor\v8'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Win/clang-373424-64a362e7-1.tgz .......... Done.
Traceback (most recent call last):
  File "v8/tools/clang/scripts/update.py", line 336, in <module>
    sys.exit(main())
  File "v8/tools/clang/scripts/update.py", line 332, in main
    return UpdateClang()
  File "v8/tools/clang/scripts/update.py", line 270, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "v8/tools/clang/scripts/update.py", line 230, in CopyDiaDllTo
    GetWinSDKDir()
  File "v8/tools/clang/scripts/update.py", line 204, in GetWinSDKDir
    win_sdk_dir = vs_toolchain.SetEnvironmentAndGetSDKDir()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 528, in SetEnvironmentAndGetSDKDir
    SetEnvironmentAndGetRuntimeDllDirs()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 90, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "G:\Inexor\v8\v8\build\vs_toolchain.py", line 203, in DetectVisualStudioPath
    ' not found.' % version_as_year)
Exception: Visual Studio Version 2017 (from GYP_MSVS_VERSION) not found.
Error: Command 'vpython.bat v8/tools/clang/scripts/update.py' returned non-zero exit status 1 in G:\Inexor\v8
Hook 'vpython.bat v8/tools/clang/scripts/update.py' took 17.74 secs
G:\Inexor\v8\v8>
```

**Comment by IAmNotHanni** [comment]
Looks like it can't find Visual Studio.
The rest has worked though!

**Comment by IAmNotHanni** [comment]
We will postpone this for now. If we get CEF to compile, we get V8 as well.
